### ISSUE TITLE
Allow flashing of generic targets (without any json pin config)

### ISSUE THREAD

**Issue by neuhausj** [ExpressLRS/web-flasher#15]
It would be nice to be able to flash generic targets directly. It could be particularly useful for DIY boards.
This would allow to load a custom json pin config file easily afterward (via the hardware.html page).

It is currently not possible, neither with the classic ExpressLRS configurator nor this tool.

An additional improvement would be to specify the json file as well when using a generic target.

Thank you

**Comment by pkendall64** [comment]
I've made some changes that allow a user to drag-n-drop a JSON hardware layout file onto the banner to flash a device.
Once the JSON is uploaded a popup will appear asking which type of firmware to upload.
![Screenshot 2023-09-10 at 3 42 42 PM](https://github.com/ExpressLRS/web-flasher/assets/512740/49bb39be-c590-486a-b3bc-df4eebe76da2)
After selecting that it takes you to page 2 where you can select the usual options before flashing.
