### ISSUE TITLE
[feature request] link to lua script

### ISSUE THREAD

**Issue by nerdCopter** [ExpressLRS/web-flasher#16]
link to download latest lua script may be useful in the WebUI

**Comment by pkendall64** [comment]
Finally, I've done it 😄

**Comment by nerdCopter** [comment]
if user sets target fields, then clicks to download the lua, then the fields reset and no download.
it only downloads when fields are empty.

**Comment by pkendall64** [comment]
> if user sets target fields, then clicks to download the lua, then the fields reset and no download. it only downloads when fields are empty.

Thanks dude, sorry it took so long for me to fix 😅
