### ISSUE TITLE
Web-flasher working as a web app in Chromium/Linux but not in Chrome/Android

### ISSUE THREAD

**Issue by LoakAudio** [ExpressLRS/web-flasher#32]
Hi all,
I hope to be in the right place.
I can install the ELRS web-flasher as a web app in Chromium (Linux Debian 12 computer) but I can't in Chrome in an Android 14 Samsung A6+ tablet. The option is not proposed. 
No problem with BlueJay ESC-Configurator or Betaflight BBE or Betaflight Configurator, even if this last one doesn't work in Android.
I don't know if it's a bug or a choice, but web apps are easier to manage in Android for me than shortcuts on the home page of the tablet.
If you can do something ...

Thanks

**Comment by pkendall64** [comment]
I have no idea how to do this and don't have any android devices to test with.

**Comment by LoakAudio** [comment]
These are indeed 2 good reasons.
I can live with that.
Thanks.

**Comment by pkendall64** [comment]
> it should work the same on any device, PWA was never supported so far so idk how it worked on your pc
> 
> can do it with this for example: https://vite-pwa-org.netlify.app/

If you have some knowledge in this area, I'm 100% open to PRs for this.

**Comment by j4k0xb** [comment]
Could you try if this works as expected? https://j4k0xb.github.io/web-flasher/
Added bonus is it can be used offline (everything in the hardware selection, .bin files after being fetched for the first time)

![image](https://github.com/user-attachments/assets/2ffb7ad6-b40e-4dfa-9607-f0d4edb2b1fd)
![image](https://github.com/user-attachments/assets/d168a3e2-aa89-4f74-bf5c-a5cd3163aa60)

**Comment by pkendall64** [comment]
Thats really nice. I tried it on the Mac and worked pefectly.

**Comment by pkendall64** [comment]
@j4k0xb more than happy for you PR these changes when you're ready

**Comment by LoakAudio** [comment]
Hi guys,
Tested with Android 14 and it works fine on a tablet.
Firmware compiled and downloaded fine.
Many thanks
